name: flutter_piano
description: A Cross platform Midi Piano built with Flutter.
maintainer: Rody Davis Jr <rody.davis.jr@gmail.com>
homepage: https://github.com/rodydavis/flutter_piano
version: 1.6.0+401
publish_to: none
environment:
  sdk: ">=3.0.0-171.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  dart_melty_soundfont: ^1.1.5
  raw_sound: ^0.3.0+1
  recase: ^4.1.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  dart_melty_soundfont:
    git:
      url: https://github.com/rodydavis/dart_melty_soundfont

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/Piano.sf2
